# Generated by Django 4.0.4 on 2022-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localId', models.CharField(max_length=200)),
                ('idToken', models.CharField(max_length=200)),
            ],
        ),
    ]
